[GH-240] Ability to work with Nix cache in read-only mode for builds we don't want to authorize in AWS.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,32 +58,49 @@ jobs:
       AWS_ACCOUNT_ID: "070427263827"
       SSM_CONFIG_PATH: /github-action-runners/nil-githhub-actions/runners/config
       S3_LOCATION_NIX_CACHE: s3://nil-githhub-actions-nix-cache-qrba32i47dik503juihjai4x
+      NIX_CACHE_KEY_PUB: nil-nix-cache:LX95txIkFncQOsRIXc3KjQkdjikbxDlSFISV/s9+aps=
     steps:
       - name: Checkout local actions
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Configure AWS credentials via OIDC
+      - name: Try configure AWS credentials via OIDC
+        continue-on-error: true
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions/gha_nix_cache
           aws-region: eu-west-2
           role-duration-seconds: 7200 # 2h
+          retry-max-attempts: 3
+
+      - name: Decide write flag
+        id: calculate_write_flag
+        run: if [[ -n "$AWS_ACCESS_KEY_ID" ]]; then echo "has_write=1" >> "$GITHUB_OUTPUT"; fi
 
       - name: Show AWS identity
+        if: steps.calculate_write_flag.outputs.has_write
         run: aws sts get-caller-identity
 
-      - name: Get nix_cache_key_pub from SSM
-        id: get_nix_cache_key_pub
+      # The source of truth for nix_cache_key_pub is SSM. But we cannot read values from it anonymously.
+      # Since this is a public key, it is acceptable to hardcode it directly in the workflow. Additionally, we can use
+      # OIDC authorized runs to verify that our hardcoded value is not outdated.
+      - name: Compare NIX_CACHE_KEY_PUB hardcode with value saved in SSM
+        if: steps.calculate_write_flag.outputs.has_write
         run: |
           param=$(aws ssm get-parameter \
             --name arn:aws:ssm:${{ env.AWS_REGION }}:${{ env.AWS_ACCOUNT_ID }}:parameter${{ env.SSM_CONFIG_PATH }}/nix_cache_key_pub \
             --with-decryption \
             | jq -r '.Parameter.Value')
-          echo "NIX_CACHE_KEY_PUB=$param" >>"$GITHUB_OUTPUT"
+          test "${{ env.NIX_CACHE_KEY_PUB }}" == "$param" || { \
+            echo "ERROR: NIX_CACHE_KEY_PUB hardcoded value does not match" \
+            "the reference stored in SSM ('$param'). The SSM value should be considered" \
+            "authoritative. Please update the hardcoded value in the workflow file.";
+            exit 1; \
+          }
 
       - name: Get nix_cache_key_sec from SSM
+        if: steps.calculate_write_flag.outputs.has_write
         id: get_nix_cache_key_sec
         run: |
           param=$(aws ssm get-parameter \
@@ -93,6 +110,7 @@ jobs:
           echo "$param" | sudo cp /dev/stdin /private/nix-signing-key
 
       - name: Create /etc/nix/upload-to-cache.sh
+        if: steps.calculate_write_flag.outputs.has_write
         run: |
           sudo mkdir -p /etc/nix
           sudo tee /etc/nix/upload-to-cache.sh <<EOL
@@ -107,6 +125,7 @@ jobs:
           sudo chmod a+x /etc/nix/upload-to-cache.sh
 
       - name: Expose AWS credentials to the nix-daemon
+        if: steps.calculate_write_flag.outputs.has_write
         run: |
           sudo launchctl setenv AWS_ACCESS_KEY_ID     "$AWS_ACCESS_KEY_ID"
           sudo launchctl setenv AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
@@ -123,8 +142,8 @@ jobs:
           extra_nix_config: |
             max-jobs = 1
             extra-substituters = ${{ env.S3_LOCATION_NIX_CACHE }}?region=${{ env.AWS_REGION }}
-            extra-trusted-public-keys = ${{ steps.get_nix_cache_key_pub.outputs.NIX_CACHE_KEY_PUB }}
-            post-build-hook = /etc/nix/upload-to-cache.sh
+            extra-trusted-public-keys = ${{ env.NIX_CACHE_KEY_PUB }}
+            ${{ steps.calculate_write_flag.outputs.has_write && 'post-build-hook = /etc/nix/upload-to-cache.sh' }}
 
       - name: Show /etc/nix/nix.conf
         run: cat /etc/nix/nix.conf
@@ -136,7 +155,7 @@ jobs:
         run: nix build .#checks.${{ matrix.platform.nixArch }}.${{ matrix.check == 'nil' && 'others' || matrix.check }} -L
 
       - name: Upload nil binary as artifact
-        if: github.event_name == 'workflow_dispatch'
+        if: github.event_name == 'workflow_dispatch' && matrix.check == 'clijs'
         uses: actions/upload-artifact@v4
         with:
           name: clijs-darwin-${{ matrix.platform.arch }}
